# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_exec', models.BooleanField(default=False)),
                ('is_committee', models.BooleanField(default=False)),
                ('eligible_class', models.IntegerField(choices=[(0, 'All Classes'), (1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField(choices=[(0, 'Yes'), (2, 'No'), (1, 'Maybe')])),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Office')),
                ('sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Sister')),
            ],
            options={
                'ordering': ['office', 'interest'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='officeinterest',
            unique_together=set([('sister', 'office')]),
        ),
    ]
