# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('elections', '0002_loi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Office')),
                ('sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Sister')),
            ],
        ),
        migrations.AlterModelOptions(
            name='loi',
            options={'ordering': ['office']},
        ),
        migrations.AddField(
            model_name='slate',
            name='vote_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_1', to='elections.Loi'),
        ),
        migrations.AddField(
            model_name='slate',
            name='vote_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_2', to='elections.Loi'),
        ),
        migrations.AlterUniqueTogether(
            name='slate',
            unique_together=set([('sister', 'office')]),
        ),
    ]
