# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_officeinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeinterest',
            options={'ordering': ['office', 'interest']},
        ),
        migrations.AlterField(
            model_name='officeinterest',
            name='interest',
            field=models.IntegerField(choices=[(0, 'Yes'), (2, 'No'), (1, 'Maybe')]),
        ),
    ]
