# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170122_1947'),
        ('elections', '0003_auto_20170128_0052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='officeinterest',
            unique_together=set([('sister', 'office')]),
        ),
    ]
