# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20170128_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='eligible_class',
            field=models.IntegerField(choices=[(0, 'All Classes'), (1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')], default=0),
        ),
        migrations.AddField(
            model_name='office',
            name='reports_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='elections.Office'),
        ),
    ]
