# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20170129_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='reports_to',
        ),
    ]
