# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-01 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_electionsettings_ois_results_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeinterest',
            options={'ordering': ['office', 'interest', 'sister']},
        ),
    ]
