# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_electionsettings_loi_results_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slate',
            name='vote_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_1', to='elections.Loi'),
        ),
        migrations.AlterField(
            model_name='slate',
            name='vote_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_2', to='elections.Loi'),
        ),
    ]
