# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170122_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sister',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Alum'), (2, 'New Member'), (4, 'Abroad'), (5, 'Deaffiliated')]),
        ),
    ]
