# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0)),
                ('is_freebie', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Event')),
                ('sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Sister')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['-year', 'term'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semester'),
        ),
        migrations.AddField(
            model_name='event',
            name='sisters_attended',
            field=models.ManyToManyField(blank=True, related_name='sisters_attended', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='event',
            name='sisters_excused',
            field=models.ManyToManyField(blank=True, related_name='sisters_excused', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='event',
            name='sisters_freebied',
            field=models.ManyToManyField(blank=True, related_name='sisters_freebied', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='event',
            name='sisters_required',
            field=models.ManyToManyField(blank=True, related_name='sisters_required', to='general.Sister'),
        ),
    ]
