# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
                ('sisters_attended', models.ManyToManyField(blank=True, related_name='sisters_attended', to='general.Sister')),
                ('sisters_excused', models.ManyToManyField(blank=True, related_name='sisters_excused', to='general.Sister')),
                ('sisters_required', models.ManyToManyField(blank=True, related_name='sisters_required', to='general.Sister')),
            ],
        ),
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Event')),
                ('sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Sister')),
            ],
        ),
    ]
