# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=1000)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semester')),
                ('sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Sister')),
            ],
        ),
    ]
