# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(0, 'Fall'), (1, 'Spring')], default=1)),
                ('year', models.IntegerField(choices=[(2017, '2017'), (2018, '2018')], default=2017)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Semester'),
        ),
    ]
