# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170110_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='required_sisters',
            field=models.ManyToManyField(blank=True, related_name='sisters_required', to='attendance.Sister'),
        ),
    ]
