# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170119_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=6),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(),
        ),
    ]
