# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_event_required_sisters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='required_sisters',
            field=models.ManyToManyField(related_name='sisters_required', to='attendance.Sister'),
        ),
    ]
