# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20170110_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='isMandatory',
            new_name='is_mandatory',
        ),
        migrations.AddField(
            model_name='event',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
