# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20170127_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='excuse',
            name='is_freebie',
            field=models.BooleanField(default=False),
        ),
    ]
