# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20170110_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sisters_attended',
            field=models.ManyToManyField(blank=True, related_name='Attendees', to='attendance.Sister'),
        ),
    ]
