# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170122_1947'),
        ('attendance', '0007_excuse_is_freebie'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sisters_freebied',
            field=models.ManyToManyField(blank=True, related_name='sisters_freebied', to='general.Sister'),
        ),
    ]
