# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_event_sisters_attended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Denied')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Event')),
                ('sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Sister')),
            ],
        ),
    ]
