# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_excuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sisters_excused',
            field=models.ManyToManyField(blank=True, related_name='sisters_excused', to='attendance.Sister'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0),
        ),
    ]
