# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20170115_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
