# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_event_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='required_sisters',
            new_name='sisters_required',
        ),
        migrations.AlterField(
            model_name='event',
            name='sisters_attended',
            field=models.ManyToManyField(blank=True, related_name='sisters_attended', to='attendance.Sister'),
        ),
    ]
