# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20170116_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='sister',
            name='class_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
