# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_sister_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.IntegerField(),
        ),
    ]
